name       : elixir
version    : 1.8.1
release    : 38
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.8.1.tar.gz : de8c636ea999392496ccd9a204ccccbc8cb7f417d948fd12692cda2bd02d9822
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    export LC_ALL=en_US.utf8
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
