name       : elixir
version    : 1.6.6
release    : 32
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.6.6.tar.gz : 74507b0646bf485ee3af0e7727e3fdab7123f1c5ecf2187a52a928ad60f93831
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    export LC_ALL=en_US.utf8
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
