name       : elixir
version    : 1.5.1
release    : 26
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.5.1.tar.gz : 9a903dc71800c6ce8f4f4b84a1e4849e3433e68243958fd6413a144857b61f6a
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    export LC_ALL=en_US.utf8
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
