name       : elixir
version    : 1.4.0
release    : 19
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.4.0.tar.gz : 34a6747b5db75c35e542805b75a08bc1b2b0a53b5180f33de6af0bdff870e6b3
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
