name       : elixir
version    : 1.2.0
release    : 5
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.2.0.tar.gz : 9f68ee5213b883c91f2f521df1f773ceec5913dbf075f7781b57ac97543e7268
license    : Apache-2.0
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps:
    - erlang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    make clean
