name       : elixir
version    : 1.6.1
release    : 28
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.6.1.tar.gz : 91109a1774e9040fb10c1692c146c3e5a102e621e9c48196bfea7b828d54544c
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    export LC_ALL=en_US.utf8
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
