name       : elixir
version    : 1.7.4
release    : 36
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.7.4.tar.gz : c7c87983e03a1dcf20078141a22355e88dadb26b53d3f3f98b9a9268687f9e20
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    export LC_ALL=en_US.utf8
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
