name       : elixir
version    : 1.2.6
release    : 10
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.2.6.tar.gz : 2fd4ed9d7d8b4bd9f151cdaf6b39726d64d7cf756186a5c9454867514e5b0916
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    make clean
