name       : elixir
version    : 1.3.4
release    : 17
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.3.4.tar.gz : f5ee5353d8dbe610b1dfd276d22f2038d57d9a7d3cea69dac10da2b098bd2033
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
