name       : elixir
version    : 1.3.1
release    : 12
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.3.1.tar.gz : c4ab90a0d8d7ed4159dd6b7e1bcbcdbdb8c6177a35328d774fccf00346b4b42c
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    make clean
