name       : elixir
version    : 1.2.1
release    : 6
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.2.1.tar.gz : 9def4c1ee8eede93bf7e64c1861956dc30b2edda233fef423b790c4b31aeda54
license    : Apache-2.0
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps:
    - erlang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    make clean
