name       : elixir
version    : 1.6.2
release    : 29
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.6.2.tar.gz : 64779258e60ddf220fde75c9d972c00ff7760cbd0edbe555c93e3f892f8b0726
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    export LC_ALL=en_US.utf8
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
