name       : elixir
version    : 1.4.4
release    : 23
source     :
    - https://github.com/elixir-lang/elixir/archive/v1.4.4.tar.gz : 2d9d5faee079949f780c8f6a1ccba015d64ecf859ed87384ae4239d69be60142
license    : Apache-2.0
component  : programming
summary    : Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
description: |
    Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
builddeps  :
    - erlang
rundeps    :
    - erlang
build      : |
    %make LIBDIR=lib64
install    : |
    %make_install PREFIX=/usr LIBDIR=lib64
    make clean
